[[copy]]
source = "static"
dest = "."

[[assets]]
file = "static/CV.pdf" 

[[assets]]
file = "assets/thesis.pdf"

[[assets]]
file = "static/404.html"

[[assets]]
file = "static/fonts/Comic-Code-Medium.otf"

[build]
target = "index.html"
dist = "dist"
